<a href="https://colab.research.google.com/github/Sweetmoon11/ideam-data/blob/main/ideam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
uploaded = files.upload()

Saving Catálogo_Nacional_de_Estaciones_del_IDEAM_20260318.csv to Catálogo_Nacional_de_Estaciones_del_IDEAM_20260318.csv

In [6]:
nombre_archivo = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[nombre_archivo]))

df.head()

,Codigo,Nombre,Categoria,Tecnologia,Estado,Departamento,Municipio,Ubicación,Altitud,LONGITUD,LATITUD,Fecha_instalacion,Fecha_suspension,Area Operativa,Corriente,Area Hidrografica,Zona Hidrografica,Subzona hidrografica,Entidad
0,23187060,VIJAGUAL [23187060],Limnimétrica,Convencional,Suspendida,Santander,Puerto Wilches,"(-73.81666667, 7.85)",56,-73.816667,7.850000,15/07/1971,15/03/1980,Area Operativa 08 - Santanderes-Arauca,Magdalena,Magdalena Cauca,Medio Magdalena,Río Lebrija y otros directos al Magdalena,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
1,52040130,LICEO LA MERCED [52040130],Pluviométrica,Convencional,Suspendida,Nariño,Pasto,"(-77.28333333, 1.216666667)","2,380",-77.283333,1.216667,15/01/1941,15/05/1966,Area Operativa 07 - Nariño-Putumayo,NaN,Pacifico,Patía,Río Juananbú,ESTACIONES PARTICULARES
2,47040010,BASE NAVAL LEGUIZA [47040010],Pluviométrica,Convencional,Suspendida,Putumayo,Puerto Leguízamo,"(-74.76666667, -0.2)",147,-74.766667,-0.200000,15/02/1974,15/11/1975,Area Operativa 07 - Nariño-Putumayo,NaN,Amazonas,Putumayo,Río Putumayo Directos (mi),INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
3,26070920,LLANITOS LOS [26070920],Pluviométrica,Convencional,Activa,Valle Del Cauca,Palmira,"(-76.45, 3.516666667)",960,-76.450000,3.516667,15/04/1973,NaN,Area Operativa 09 - Cauca-Valle-Caldas,NaN,Magdalena Cauca,Cauca,Río Guachal (Bolo - Fraile y Párraga),ESTACIONES PARTICULARES
4,29037440,CERRITOS LOS [29037440],Limnimétrica,Convencional,Suspendida,Bolivar,María La Baja,"(-75.38333333, 10.05)",3,-75.383333,10.050000,15/06/1978,15/11/1982,Area Operativa 02 - Atlántico-Bolivar-Sucre,CIÉNAGA MARIA LA BAJA,Magdalena Cauca,Bajo Magdalena,Canal del Dique margen izquierda,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...

In [7]:

print(df.isnull().sum())

Codigo                     0
Nombre                     0
Categoria                  0
Tecnologia                 0
Estado                     0
Departamento               0
Municipio                  0
Ubicación                  0
Altitud                    0
LONGITUD                   0
LATITUD                    0
Fecha_instalacion        133
Fecha_suspension        5719
Area Operativa             0
Corriente               6253
Area Hidrografica          0
Zona Hidrografica          0
Subzona hidrografica       0
Entidad                    0
dtype: int64

In [11]:
# 1. Tratamos los nulos de Fecha_suspension y Corriente
df['Fecha_suspension'] = df['Fecha_suspension'].fillna('ESTACION_ACTIVA')
df['Corriente'] = df['Corriente'].fillna('DATO_FALTANTE')

# 2. Para los 133 de Fecha_instalacion, los llenamos con la fecha más antigua
# o simplemente un texto descriptivo
df['Fecha_instalacion'] = df['Fecha_instalacion'].fillna('01/01/1900')

# 3. Verificamos que ya no queden nulos
print("Nuevos conteos de nulos:")
print(df.isnull().sum())

Nuevos conteos de nulos:
Codigo                  0
Nombre                  0
Categoria               0
Tecnologia              0
Estado                  0
Departamento            0
Municipio               0
Ubicación               0
Altitud                 0
LONGITUD                0
LATITUD                 0
Fecha_instalacion       0
Fecha_suspension        0
Area Operativa          0
Corriente               0
Area Hidrografica       0
Zona Hidrografica       0
Subzona hidrografica    0
Entidad                 0
dtype: int64

In [9]:
# Llenamos los vacíos con una fecha ficticia muy lejana o un texto
df['Fecha_suspension'] = df['Fecha_suspension'].fillna('ACTIVA')

In [10]:
# Rellenar con un valor genérico
df['Corriente'] = df['Corriente'].fillna('SIN ESPECIFICAR')

In [12]:
# Limpiar columnas de texto principales
columnas_texto = ['Departamento', 'Municipio', 'Tecnologia', 'Estado', 'Entidad']

for col in columnas_texto:
    df[col] = df[col].astype(str).str.upper().str.strip()

In [15]:
%load_ext google.colab.data_table

# Muestra las primeras 20 filas
df.head(20)

,Codigo,Nombre,Categoria,Tecnologia,Estado,Departamento,Municipio,Ubicación,Altitud,LONGITUD,LATITUD,Fecha_instalacion,Fecha_suspension,Area Operativa,Corriente,Area Hidrografica,Zona Hidrografica,Subzona hidrografica,Entidad
0,23187060,VIJAGUAL [23187060],Limnimétrica,CONVENCIONAL,SUSPENDIDA,SANTANDER,PUERTO WILCHES,"(-73.81666667, 7.85)",56,-73.816667,7.850000,1971-07-15,1980-03-15 00:00:00,Area Operativa 08 - Santanderes-Arauca,Magdalena,Magdalena Cauca,Medio Magdalena,Río Lebrija y otros directos al Magdalena,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
1,52040130,LICEO LA MERCED [52040130],Pluviométrica,CONVENCIONAL,SUSPENDIDA,NARIÑO,PASTO,"(-77.28333333, 1.216666667)","2,380",-77.283333,1.216667,1941-01-15,1966-05-15 00:00:00,Area Operativa 07 - Nariño-Putumayo,SIN ESPECIFICAR,Pacifico,Patía,Río Juananbú,ESTACIONES PARTICULARES
2,47040010,BASE NAVAL LEGUIZA [47040010],Pluviométrica,CONVENCIONAL,SUSPENDIDA,PUTUMAYO,PUERTO LEGUÍZAMO,"(-74.76666667, -0.2)",147,-74.766667,-0.200000,1974-02-15,1975-11-15 00:00:00,Area Operativa 07 - Nariño-Putumayo,SIN ESPECIFICAR,Amazonas,Putumayo,Río Putumayo Directos (mi),INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
3,26070920,LLANITOS LOS [26070920],Pluviométrica,CONVENCIONAL,ACTIVA,VALLE DEL CAUCA,PALMIRA,"(-76.45, 3.516666667)",960,-76.450000,3.516667,1973-04-15,ACTIVA,Area Operativa 09 - Cauca-Valle-Caldas,SIN ESPECIFICAR,Magdalena Cauca,Cauca,Río Guachal (Bolo - Fraile y Párraga),ESTACIONES PARTICULARES
4,29037440,CERRITOS LOS [29037440],Limnimétrica,CONVENCIONAL,SUSPENDIDA,BOLIVAR,MARÍA LA BAJA,"(-75.38333333, 10.05)",3,-75.383333,10.050000,1978-06-15,1982-11-15 00:00:00,Area Operativa 02 - Atlántico-Bolivar-Sucre,CIÉNAGA MARIA LA BAJA,Magdalena Cauca,Bajo Magdalena,Canal del Dique margen izquierda,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
5,21209530,EMBALSE LOS TUNJOS [21209530],Limnimétrica,CONVENCIONAL,ACTIVA,BOGOTÁ,"BOGOTÁ, D.C","(-74.2, 4.283333333)","3,500",-74.200000,4.283333,1988-03-15,ACTIVA,Area Operativa 11 - Cundinamarca-Amazonas,Chisaca,Orinoco,Meta,Río Guayuriba,EMPRESA DE ACUEDUCTO Y ALCANTARILLADO DE BOGOT...
6,2615700040,AGUAS DE MANIZALES - AUT [2615700040],Limnigráfica,AUTOMÁTICA CON TELEMETRÍA,ACTIVA,CALDAS,MANIZALES,"(-75.490305556, 5.089916667)","1,659",-75.490306,5.089917,2018-07-04,ACTIVA,Area Operativa 09 - Cauca-Valle-Caldas,QUEBRADA EL GUAMO,Magdalena Cauca,Cauca,Río Chinchiná,CORPORACIÓN AUTÓNOMA REGIONAL DE CALDAS
7,24017390,PTE CALICANTO [24017390],Limnimétrica,CONVENCIONAL,SUSPENDIDA,CUNDINAMARCA,SUSA,"(-73.8, 5.45)","2,550",-73.800000,5.450000,1964-04-15,1966-12-15 00:00:00,Area Operativa 11 - Cundinamarca-Amazonas,Susa,Magdalena Cauca,Sogamoso,Río Suárez,CORPORACION AUTONOMA REGIONAL DE CUNDINAMARCA
8,29010090,BASURA LA [29010090],Pluviométrica,CONVENCIONAL,SUSPENDIDA,BOLIVAR,SAN JACINTO,"(-75.11666667, 9.816666667)",300,-75.116667,9.816667,1972-01-15,1972-08-15 00:00:00,Area Operativa 02 - Atlántico-Bolivar-Sucre,SIN ESPECIFICAR,Magdalena Cauca,Bajo Magdalena,Directos al Bajo Magdalena entre El Plato y Ca...,INSTITUTO COLOMBIANO DE LA REFORMA AGRARIA
9,23087490,GUATAPE RN 9A [23087490],Limnigráfica,CONVENCIONAL,ACTIVA,ANTIOQUIA,SAN RAFAEL,"(-75.03333333, 6.3)",982,-75.033333,6.300000,1986-03-15,ACTIVA,Area Operativa 01 - Antioquia-Chocó,Guatape,Magdalena Cauca,Medio Magdalena,Río Nare,EMPRESAS PÚBLICAS DE MEDELLIN E.S.P.
10,13070390,CIENAGA DE ORO [13070390],Pluviométrica,CONVENCIONAL,ACTIVA,CORDOBA,CIÉNAGA DE ORO,"(-75.63, 8.87)",25,-75.630000,8.870000,1965-08-15,ACTIVA,Area Operativa 02 - Atlántico-Bolivar-Sucre,SIN ESPECIFICAR,Caribe,Sinú,Bajo Sinú,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
11,26090470,MIRAFLORES [26090470],Pluviométrica,CONVENCIONAL,SUSPENDIDA,VALLE DEL CAUCA,BUGA,"(-76.21666667, 3.85)","1,824",-76.216667,3.850000,1971-01-15,1972-04-15 00:00:00,Area Operativa 09 - Cauca-Valle-Caldas,SIN ESPECIFICAR,Magdalena Cauca,Cauca,Ríos Guadalajara y San Pedro,CORPORACION AUTONOMA REGIONAL DEL VALLE DEL CAUCA
12,26170010,PUEBLORRICO [26170010],Pluviométrica,CONVENCIONAL,SUSPENDIDA,ANTIOQUIA,PUEBLORRICO,"(-75.85, 5.783333333)","1,942",-75.850000,5.783333,1922-01-15,1960-09-15 00:00:00,Area Operativa 01 - Antioquia-Chocó,SIN ESPECIFICAR,Magdalena Cauca,Cauca,Río Frío y Otros Directos al Cauca,ESTADÍSTICA DEPARTAMENTAL DE ANTIOQUIA
13,26010070,LAGUNA SAN RAFAEL [26010070],Pluviométrica,CONVENCIONAL,SUSPENDIDA,CAUCA,PURACÉ (COCONUCO),"(-76.38333333, 2.383333333)","3,420",-76.383333,2.383333,1970-02-15,2000-12-15 00:00:00,Area Operativa 09 - Cauca-Valle-Caldas,SIN ESPECIFICAR,Magdalena Cauca,Cauca,Alto Río Cauca,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
14,21097040,CANAL SURTIDOR [21097040],Limnimétrica,CONVENCIONAL,SUSPENDIDA,HUILA,PALERMO,"(-75.36666667, 2.833333333)",440,-75.366667,2.833333,1968-12-15,1970-12-15 00:00:00,Area Operativa 04 - Huila-Caquetá,QUEBRADA FAJARITO,Magdalena Cauca,Alto Magdalena,Juncal y otros Rios directos al Magdalena,INSTITUTO COLOMBIANO DE LA REFORMA AGRARIA
15,24037050,CENTRAL TERMOPAIPA [24037050],Limnimétrica,CONVENCIONAL,SUSPENDIDA,BOYACÁ,PAIPA,"(-73.13333333, 5.766666667)","2,580",-73.133333,5.766667,1955-01-15,1959-04-15 00:00:00,Area Operativa 06 - Boyacá-Casanare-Vichada,Chicamocha,Magdalena Cauca,Sogamoso,Río Chicamocha,INSTITUTO COLOMBIANO DE ENERGÍA ELÉCTRICA (ELE...
16,27017350,YARUMITO RMS 14 [27017350],Limnigráfica,CONVENCIONAL,ACTIVA,ANTIOQUIA,BARBOSA,"(-75.28333333, 6.466666667)","1,740",-75.283333,6.466667,1972-04-15,ACTIVA,Area Operativa 01 - Antioquia-Chocó,Medellin,Magdalena Cauca,Nechí,Río Porce,EMPRESAS PÚBLICAS DE MEDELLIN E.S.P.
17,21201840,LAG DEL INDIO [21201840],Pluviométrica,CONVENCIONAL,ACTIVA,CUNDINAMARCA,VIOTÁ,"(-74.46666667, 4.4)","2,050",-74.466667,4.400000,1989-04-15,ACTIVA,Area Operativa 10 - Tolima,SIN ESPECIFICAR,Magdalena Cauca,Alto Magdalena,Río Bogotá,CORPORACION AUTONOMA REGIONAL DE CUNDINAMARCA
18,23110040,TRIQUE EL [23110040],Pluviométrica,CONVENCIONAL,ACTIVA,BOYACÁ,PUERTO BOYACÁ,"(-74.56834167, 5.880888889)",179,-74.568342,5.880889,1974-08-15,ACTIVA,Area Operativa 10 - Tolima,SIN ESPECIFICAR,Magdalena Cauca,Medio Magdalena,Directos al Magdalena Medio entre ríos Negro,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...
19,21206170,CLARETIANO [21206170],Climatológica Ordinaria,CONVENCIONAL,SUSPENDIDA,BOGOTÁ,"BOGOTÁ, D.C","(-74.2, 4.6)","2,500",-74.200000,4.600000,1984-08-15,1985-08-15 00:00:00,Area Operativa 11 - Cundinamarca-Amazonas,SIN ESPECIFICAR,Magdalena Cauca,Alto Magdalena,Río Bogotá,INSTITUTO DE HIDROLOGÍA METEOROLOGÍA Y ESTUDIO...

In [17]:
# Resumen técnico de la limpieza
print("--- Resumen de Datos Faltantes ---")
print(df.isnull().sum())

print("\n--- Tipos de Datos por Columna ---")
print(df.dtypes)

--- Resumen de Datos Faltantes ---
Codigo                  0
Nombre                  0
Categoria               0
Tecnologia              0
Estado                  0
Departamento            0
Municipio               0
Ubicación               0
Altitud                 0
LONGITUD                0
LATITUD                 0
Fecha_instalacion       0
Fecha_suspension        0
Area Operativa          0
Corriente               0
Area Hidrografica       0
Zona Hidrografica       0
Subzona hidrografica    0
Entidad                 0
dtype: int64

--- Tipos de Datos por Columna ---
Codigo                           int64
Nombre                          object
Categoria                       object
Tecnologia                      object
Estado                          object
Departamento                    object
Municipio                       object
Ubicación                       object
Altitud                         object
LONGITUD                       float64
LATITUD                        float64
Fecha_instalacion       datetime64[ns]
Fecha_suspension                object
Area Operativa                  object
Corriente                       object
Area Hidrografica               object
Zona Hidrografica               object
Subzona hidrografica            object
Entidad                         object
dtype: object

In [18]:
# Ver cuántas estaciones hay por cada departamento
print(df['Departamento'].value_counts())

# Ver si hay nombres repetidos o extraños en 'Estado'
print(df['Estado'].unique())

Departamento
ANTIOQUIA                                                   1251
CUNDINAMARCA                                                1111
VALLE DEL CAUCA                                              830
BOYACÁ                                                       535
SANTANDER                                                    519
TOLIMA                                                       498
CALDAS                                                       416
CAUCA                                                        386
HUILA                                                        365
BOGOTÁ                                                       355
BOLIVAR                                                      317
NORTE DE SANTANDER                                           296
CESAR                                                        275
CORDOBA                                                      229
RISARALDA                                                    218
LA GUAJIRA                                                   214
META                                                         203
MAGDALENA                                                    200
NARIÑO                                                       165
CHOCO                                                        129
ATLANTICO                                                    127
QUINDÍO                                                      116
PUTUMAYO                                                     105
SUCRE                                                         98
CASANARE                                                      96
AMAZONAS                                                      60
VICHADA                                                       60
CAQUETA                                                       60
ARAUCA                                                        45
ARCHIPIELAGO DE SAN ANDRES, PROVIDENCIA Y SANTA CATALINA      26
VAUPES                                                        19
GUAINÍA                                                       18
GUAVIARE                                                      17
Name: count, dtype: int64
['SUSPENDIDA' 'ACTIVA' 'EN MANTENIMIENTO']

In [19]:
# Convertimos Altitud a número, los errores se vuelven NaN y luego se llenan con 0
df['Altitud'] = pd.to_numeric(df['Altitud'], errors='coerce').fillna(0)

In [20]:
# Exportamos a JSON
# 'records' crea una lista de objetos: [{col1: val1, col2: val2}, ...]
df.to_json('estaciones_limpias.json', orient='records', force_ascii=False, indent=4)

# Descargar el archivo automáticamente
from google.colab import files
files.download('estaciones_limpias.json')